apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-v7t8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-v7t8
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-v7t8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-v7t8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-v7t8
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dezo-tenant/rhtap-demo-app/hacbs-test-project-v7t8@sha256:4f2a2c1aca2380b43c5b28845683a7d2ea84962578573a81f9d0af52dd985806
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
